name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3

      - name: Setup .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore 
        run: dotnet restore ./PasswordMaker.sln 

      - name: Build
        run: dotnet build ./PasswordMaker.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./PasswordMaker.sln --configuration Release --no-build
